apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certbot-conf-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: certbot-conf-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certbot-www-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: certbot-www-pv
  resources:
    requests:
      storage: 1Gi