apiVersion: v1
kind: Service
metadata:
  name: nginx-terminate-service
spec:
  selector:
    app: nginx-terminate
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
