#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: certbot-conf-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#  storageClassName: standard-rwo
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: certbot-www-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#  storageClassName: standard-rwo